version: "3.8"
services:

  db:
    image: mysql
    container_name: mysql_$CONTAINER_NAME
    restart: always
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - networkName
  adminer:
    image: adminer:4-standalone
    container_name: adminer_$CONTAINER_NAME
    depends_on:
      - db
    env_file:
      - .env
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_adminer.entrypoints=http"
      - "traefik.http.routers.${PROJECT_NAME}_admin.rule=Host(`adminer-${HOST}`)"
      - "traefik.http.routers.${PROJECT_NAME}_adminer_secure.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}_adminer_secure.rule=Host(`adminer-${HOST}`)"
      - "traefik.http.routers.${PROJECT_NAME}_adminer_secure.tls=true"
    networks:
      - networkName
  mail:
    image: djfarrelly/maildev
    container_name: maildev_$CONTAINER_NAME
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${PROJECT_NAME}_mail.loadbalancer.server.port=80"
      - "traefik.http.routers.${PROJECT_NAME}_mail.entrypoints=http"
      - "traefik.http.routers.${PROJECT_NAME}_mail.rule=Host(`mail-${HOST}`)"
      - "traefik.http.routers.${PROJECT_NAME}_mail.middlewares=redirect-to-https@file"
      - "traefik.http.routers.${PROJECT_NAME}_mail_secure.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}_mail_secure.rule=Host(`mail-${HOST}`)"
      - "traefik.http.routers.${PROJECT_NAME}_mail_secure.tls=true"
    networks:
      - networkName
  web:
    build: php
    container_name: web_$CONTAINER_NAME
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${PROJECT_NAME}_web.loadbalancer.server.port=80"
      - "traefik.http.routers.${PROJECT_NAME}_web.entrypoints=http"
      - "traefik.http.routers.${PROJECT_NAME}_web.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${PROJECT_NAME}_web.middlewares=redirect-to-https@file"
      - "traefik.http.routers.${PROJECT_NAME}_web_secure.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}_web_secure.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${PROJECT_NAME}_web_secure.tls=true"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./www:/var/www
    restart: always
    networks:
      - networkName
networks:
  networkName:
    name: "${CONTAINER_NAME}_net"